image: Visual Studio 2017
build_script:
- cmd: dotnet build src --configuration Release
test_script:
- cmd: >-
    dotnet test "src\Tests\Tests.csproj" --configuration Release --no-build
artifacts:
- path: nugets\**\*.nupkg