image: Visual Studio 2017
install:
- cmd: appveyor DownloadFile https://dist.nuget.org/win-x86-commandline/v4.9.1/nuget.exe
build_script:
- cmd: dotnet build src --configuration Release
test_script:
- cmd: >-
    dotnet test "src\Tests\Tests.csproj" --configuration Release --no-build
artifacts:
- path: nugets\**\*.nupkg