image: Visual Studio 2022
environment:
  DOTNET_NOLOGO: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
build_script:
- choco install dotnet
- dotnet build src --configuration Release
- dotnet test src --configuration Release --no-build --no-restore
test: off
artifacts:
- path: nugets\**\*.nupkg